In [5]:
q0 = [1,0] #|0> state
q1 = [0,1] #|1> state
q2 = [0.7071067811865475, 0.7071067811865475] #|+> state
q3 = [0.7071067811865475, -0.7071067811865475] #|-> state
q4 = [0.7071067811865475, 0+0.7071067811865475j] #|i> state
q5 = [0.7071067811865475, 0-0.7071067811865475j] #|-i> state

In [4]:
import numpy as np

q4 = np.array([0.7071067811865475+0j, 0-0.7071067811865475j])
p4 = np.abs(q4)**2
print(p4)

[0.5 0.5]


In [5]:
q0 = [1,0]
q1 = [0,1]

combined_state = np.kron(q0,q1)
print(combined_state)

[0 1 0 0]


In [6]:
import numpy as np
# Implementing X gate
q0 = np.array([1,0])

print("Initial state:\t",q0)

X = np.array([
    [0,1],
    [1,0]
])

q0 = np.dot(X,q0)

print("Final state:\t",q0)

Initial state:	 [1 0]
Final state:	 [0 1]


In [7]:
#Implementing H gate
q0 = np.array([1,0])

print("Initial state:\t",q0)

H = np.array([
    [1/np.sqrt(2),1/np.sqrt(2)],
    [1/np.sqrt(2),-1/np.sqrt(2)]
])

q0 = np.dot(H,q0)

print("Final state:\t",q0)

Initial state:	 [1 0]
Final state:	 [0.70710678 0.70710678]


In [8]:
psi = [1, 0, 0, 0, 0, 0, 0, 0]
print("Initial state:", psi)


# Define X (NOT) gate:

X = np.array([
[0, 1],
[1, 0]
])

# Define 2x2 identity

I = np.identity(2)

# Calculate operator for X gate acting on third qubit in 3-qubit circuit

O = np.kron(np.kron(I, I), X)

print("\nOperator:\n\n", O, "\n")


# And finally, apply operator

psi = np.dot(psi, O)
print("Final state:", psi)

Initial state: [1, 0, 0, 0, 0, 0, 0, 0]

Operator:

 [[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]] 

Final state: [0. 1. 0. 0. 0. 0. 0. 0.]


In [61]:
###########################################################################################################################
#FINAL PROGRAM#
def get_ground_state(num_qubits):
    # return vector of size 2**num_qubits with all zeroes except first element which is 1
    q_gnd = [0] * 2**(num_qubits)
    q_gnd[0] = 1
    return q_gnd

def get_operator(total_qubit, gate_unitary, target_qubit):
    # return unitary operator of size 2**n x 2**n for given gate and target qubits
    # single qubit
    I = np.identity(2)
    for i in range(1,total_qubit+1):
        operator = I
        if((i == 1) & (target_qubit == 1) &(total_qubit == 1)):
            operator = gate_unitary
        if(i == target_qubit):
            operator = np.kron(operator,gate_unitary)
        operator = np.kron(operator,I)
    return operator

def run_program(initial_state, program):
    # read program, and for each gate:
    #   - calculate matrix operator
    #   - multiply state with operator
    # return final state
    return

def measure_all(state_vector):
    # choose element from state_vector using weighted random and return it's index
    return

def get_counts(state_vector, num_shots):
    # simply execute measure_all in a loop num_shots times and
    # return object with statistics in following form:
    #   {
    #      element_index: number_of_ocurrences,
    #      element_index: number_of_ocurrences,
    #      element_index: number_of_ocurrences,
    #      ...
    #   }
    # (only for elements which occoured - returned from measure_all)
    return

In [62]:
get_ground_state(2)
get_operator(2, [[0,1],[1,0]], 1)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])